//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehrsan.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkedInProfiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkedInProfiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mehrsan.Test.LinkedInProfiles", typeof(LinkedInProfiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///}&lt;/p&gt;&lt;img src=&quot;./Connections _ LinkedIn_files/1537df6.jpg&quot;&gt;&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;label&gt; See more people to contact&lt;/label&gt;&lt;/p&gt;&lt;span&gt;&lt;/span&gt;&lt;/div&gt;&lt;/div&gt;
        ///&lt;/div&gt;&lt;/div&gt;&lt;!-- Contact list section --&gt;&lt;section id=&quot;contact-list-container&quot; class=&quot;box-border&quot;&gt;&lt;header class=&quot;contact-list-header&quot;&gt;&lt;nav id=&quot;contact-list-navigation&quot;&gt;&lt;ul id=&quot;contact-list-organizer-menu&quot;&gt;&lt;li class=&quot;search-result hide&quot;&gt;Results for: &lt;strong&gt;&lt;/strong&gt;&lt;/li&gt;&lt;li class=&quot;filter&quot;&gt;&lt;dl class=&quot;dropdown filter-dropdown&quot;&gt;&lt;dt class=&quot;dropdown-anchor&quot; tabindex=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
    }
}
