//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehrsan.Dal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long Id { get; set; }
        public System.DateTime ReviewTime { get; set; }
        public int ReviewPeriod { get; set; }
        public bool Result { get; set; }
        public long WordId { get; set; }
        public long ReviewTimeSpan { get; set; }
        public string UpdatedWord { get; set; }
        public string UpdatedMeaning { get; set; }
    
        public virtual Word Word { get; set; }
    }
}
