//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehrsan.Dal.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WordEntities : DbContext
    {
        public WordEntities()
            : base("name=WordEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Graph> Graphs { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<WordFile> WordFiles { get; set; }
    
        public virtual int bpRemoveRepetitiveWords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bpRemoveRepetitiveWords");
        }
    
        public virtual int bpRemoveRepetitiveWords1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bpRemoveRepetitiveWords1");
        }
    }
}
