//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehrsan.Dal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordFile
    {
        public long Id { get; set; }
        public string CorrespondingText { get; set; }
        public long LanguageId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
